### ISSUE TITLE
Compatibility issue with AmbientSounds 3 after 1.3.0

### ISSUE THREAD

**Issue by Krampus69** [ItsBlackGear/CaveBiomeAPI#10]
Hello 👋 
So I'm trying to understand why there is a compatibility issue between the CaveBiomeAPI 1.3.0 (1.3.1 too) and the AmbientSounds 3 mod : https://www.curseforge.com/minecraft/mc-mods/ambientsounds/files

This line "Added cave biome distribution by using Biome Attributes" might be the reason why there is no ambient sounds in biomes. There is a command /ambient-debug who will show you the .ogg files that are played in the current biome (like in this example there are 3 ambient sounds working correctly on the 2.0 CaveBiomeAPI)
![2021-08-13_14 11 44](https://user-images.githubusercontent.com/81943963/129355293-2d055018-7a1f-43d1-abf5-b668258cbd59.png)

I'll try to contact the AmbientSounds creator too and try to find an explanation to this incompatibility issue, but maybe you would have an idea that could help.

Thank you for your awesome work and excellent mod, keep up the good work 👍

**Comment by Krampus69** [comment]
Forgot to say I'm using AmbientSounds_v3.1.8_mc1.16.5 & CreativeCore_v2.2.1_mc1.16.5 (latest versions for the AmbientSounds mod)

**Comment by ItsBlackGear** [comment]
sorry for the delay, if it was working with CaveBiomeAPI 2.0 then it will work again with the upcoming update

**Comment by ItsBlackGear** [comment]
this issue has been fixed with the latest version of CaveBiomeAPI c:
