### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Nubidubi23** [ItsBlackGear/CaveBiomeAPI#12]
[crash-2021-08-14_01.26.01-fml.txt](https://github.com/ItsBlackGear/CaveBiomeAPI/files/6987252/crash-2021-08-14_01.26.01-fml.txt)

**Comment by ItsBlackGear** [comment]
sorry for leaving you unread, usually i get crash reports and simple stuff in discord

**Comment by ItsBlackGear** [comment]
i'll release a new update today, so you can try with that one
