### ISSUE TITLE
The caves have no access to the surface when the Darker Depths is installed

### ISSUE THREAD

**Issue by MadeshaD** [ItsBlackGear/CaveBiomeAPI#15]
**Describe the bug**
It is impossible to enter the caves through the surface without digging, as there is no entrance to them.

**Screenshots**
![1](https://user-images.githubusercontent.com/65042032/137750577-72a1a455-314f-40fc-9c3c-fb72065567b6.png)
![2021-10-18_18 16 59](https://user-images.githubusercontent.com/65042032/137742894-c1e9fd7f-c450-4b0e-afdf-f584bc5ed482.png)
![2021-10-18_18 17 40](https://user-images.githubusercontent.com/65042032/137742926-54a55972-0df1-4164-8705-0201c88e7122.png)

**Forge version information:**
 - Minecraft: 1.16.5
 - Forge: 36.2.8
 - CaveBiomeAPI 1.4.0
 - Darker Depths 1.1.4

**Comment by ItsBlackGear** [comment]
sorry for late reply, i can confirm that this was caused because of darker depths and it was fixed during the development of the new update (which has not been released yet)

**Comment by BastardNeko** [comment]
when will the new update be released? will it be relatively soon?
