### ISSUE TITLE
mod conflict with BYG

### ISSUE THREAD

**Issue by MoonMoonShark** [ItsBlackGear/CaveBiomeAPI#17]
recently discoverd that the biomes on my server have stopped spawning correctly. after some testing, i tracked it down to CaveBiomeAPI v1.4.0 and v 1.4.1. i made a clean local install using only BYG and the Caves & Cliffs Backport (and API), for testing and found that the BYG biomes spawn correctly with API v1.3.7, but not the latest two.

**_Works Correctly:_**
Minecraft: 1.16.5
Forge: 36.2.0
Oh, the Biomes You'll Go: 1.3.5
Caves & Cliffs Backport: 7.0
CaveBiomeAPI: v1.3.7

**_Doesn't Work:_**
Minecraft: 1.16.5
Forge: 36.2.0
Oh, the Biomes You'll Go: 1.3.5
Caves & Cliffs Backport: 7.0
CaveBiomeAPI: v1.4.0 & v1.4.1

thank you for ALL of your hard work on these mods. my players have been absolutely elated to enjoy the 1.17 features while still in 1.16. please let me know if there's anything i can do to help. my server is available as a resource for further testing, if you need it.

**Comment by ItsBlackGear** [comment]
Thanks for the report! I shall look into it

**Comment by ItsBlackGear** [comment]
hmmm.. could you define what's wrong with the biome generation? i'm testing CBA along with BYG and i see no issues at all

![imagen](https://user-images.githubusercontent.com/68313143/139913057-febe0ffa-b7e8-4ac1-acc1-c3156da90c24.png)

**Comment by MoonMoonShark** [comment]
when you search for biomes, they don't appear.

a few that i've found don't appear upon searching (locatebiome)
byg:alps
byg:skyris_peaks
byg:zelkova_forest

**Comment by MoonMoonShark** [comment]
i apologize, i should have clarified. BYG biomes generally spawn, but some don't, which is the weird part. O_o i had bookmarked a location as being Alps, but then i had wiped the map and regenerated it, for an unrelated reason. upgraded to the latest version of CBA, and went back to that spot, only to find a forest instead. wiped the area, rolled back to previous version of CBA, and it was Alps again.

**Comment by ItsBlackGear** [comment]
that's weird.. i haven't touched the surface biome generation

**Comment by ItsBlackGear** [comment]
![imagen](https://user-images.githubusercontent.com/68313143/139921344-9383f10b-47cb-4652-b9fb-81f644218d00.png)
i just found alps

**Comment by ItsBlackGear** [comment]
![imagen](https://user-images.githubusercontent.com/68313143/139921436-1277eb06-9709-47e5-9fcd-3e1a4be375a6.png)
also a zelkova forest, didn't find the skyris peaks tho

**Comment by MoonMoonShark** [comment]
hmmmm.... ok, well, then why does it work for you but not me?

standing at spawn, searching for biomes: with 1.3.7

![2021-11-02_14 28 24](https://user-images.githubusercontent.com/57743121/139923918-df50370d-ee19-4b76-8a65-8062eb9781b9.png)

same game, same spot, searching for biomes: with 1.4.1

![2021-11-02_14 26 55](https://user-images.githubusercontent.com/57743121/139923994-d633dc50-b84d-423a-ad50-f334376259f8.png)

it's a brand new game, with no pre-existing configs. the only two things installed are BYG and Caves & Cliffs/CBA.

**Comment by MoonMoonShark** [comment]
what's extra super weird is that i installed Nature's Compass and it's finding biomes that /locatebiome doesn't! O_o

![2021-11-02_14 52 04](https://user-images.githubusercontent.com/57743121/139927404-867f976f-6c9b-4f21-879a-f8b1668bd745.png)

![2021-11-02_14 52 32](https://user-images.githubusercontent.com/57743121/139927408-10590904-144d-42c6-88be-8d66c8774bab.png)

**Comment by MoonMoonShark** [comment]
so, i tried teleporting to the location that nature's compass said was a skyris peak, and i arrived inside a cave. on a hunch, i tried going back to spawn, to the same location as before, but this time i went up to elevation 150, which put me above the cave, near the top of the skyris area, and now /locatebiome found both the alps and the skyris peaks! i wonder if it has something to do with the /locatebiome seeing the cave biome at that specific elevation, and not the biome of the overworld?

![2021-11-02_15 00 40](https://user-images.githubusercontent.com/57743121/139928227-1306460e-e3cd-4d9a-bc79-8223b2a051ba.png)

**Comment by MoonMoonShark** [comment]
er.... wut? ok, now minecraft is just messing with me. lol

1.3.7

![2021-11-02_15 19 47](https://user-images.githubusercontent.com/57743121/139930741-8781f8a2-3d46-466b-90c4-52895a5160d9.png)


1.4.1

![2021-11-02_15 16 32](https://user-images.githubusercontent.com/57743121/139930768-1db1c796-6cf2-4d72-a7c3-8399df99adb2.png)

**Comment by ItsBlackGear** [comment]
uhh i'm starting to think that maybe it's related to BYG 👀

**Comment by MoonMoonShark** [comment]
lol maybe minecraft is just having a midlife crisis or needs to go home and take a nap. knowing that the biomes ARE spawning, MC just can't seem to find them, i guess i'll worry less about this, and just use Nature's Compass to find them.

**Comment by ItsBlackGear** [comment]
maybe 👀 that's weird.. but that's usually linked to the biome provider
