### ISSUE TITLE
Incompatibility with DungeonCrawl 1.16.5-2.3.3

### ISSUE THREAD

**Issue by Thombias** [ItsBlackGear/CaveBiomeAPI#20]
Hey there, so DungeonCrawl just got updated and brought back compatiblity with Lootr but unfortunately the mod fails to load in my modpack. I first reported this issue on their Github but according to the developer it seems the new 2.3.3 version broke the DungeonCrawl compat from CaveBiomeAPI, which is causing DungeonCrawl to fail from loading.

Quote from the developer:
"Looks like CaveBiomeApi has introduced a compatibility module for Dungeon Crawl which broke with version 2.3.3. Their github does not seem to be up to date though, so its hard to tell what exactly it is."

I put the crash log here as a download to avoid spamming this issue with too much text:
[crash-2021-11-07_16.45.23-fml.txt](https://github.com/ItsBlackGear/CaveBiomeAPI/files/7492727/crash-2021-11-07_16.45.23-fml.txt)

**Comment by ItsBlackGear** [comment]
huh, thanks for letting me know :0 i'll make sure to fix this

**Comment by ItsBlackGear** [comment]
hello o/ this issue has been fixed!

**Comment by Thombias** [comment]
Thank you a lot! :)
