### ISSUE TITLE
Incompatibility With KubeJS "worldgen.remove" Event

### ISSUE THREAD

**Issue by wademason** [ItsBlackGear/CaveBiomeAPI#21]
When developing a modpack, the KubeJS worldgen.remove event does not remove ores.

```
onEvent('worldgen.remove', event => {
	event.removeOres(ores => {
		ores.blocks = ['minecraft:iron_ore', 'minecraft:gold_ore', 'minecraft:coal_ore', 'minecraft:nether_gold_ore', 'minecraft:nether_quartz_ore', 'minecraft:diamond_ore', 'minecraft:emerald_ore', 'minecraft:redstone_ore', 'minecraft:lapis_ore']
	})
})
```
![image](https://user-images.githubusercontent.com/6643736/140658555-1c366ec9-ae79-4f83-9353-3be8bedcaa22.png)

**Comment by ItsBlackGear** [comment]
that's from Caves & Cliffs Backport side and it's going to be fixed

**Comment by ItsBlackGear** [comment]
hello o/ this issue has been fixed now in caves and cliffs backport c:
