### ISSUE TITLE
Doesn't work with Terraforged

### ISSUE THREAD

**Issue by devjavu7** [ItsBlackGear/CaveBiomeAPI#23]
When using Terraforged as a generator, the biomes of this mod do not generate. Presumably so, as there is no biome mapping.

**Comment by ItsBlackGear** [comment]
it's a known issue, sadly it's one of the limitations that we can't workaround since terraforged uses a custom biome source system in their world generator

**Comment by devjavu7** [comment]
Damn. Is there anything that I can do as a user? Like some setting on Terraforged? Thank you for the answer.

**Comment by ItsBlackGear** [comment]
nope, nothing actually, i've tried to implement the cave biomes into terraforged a couple of times without results, also terraforged dev are aware of this

**Comment by devjavu7** [comment]
Are they willing to change it? Cause I REALLY like the mod you wrote for this API and if they are gonna change it I'll just check in a month or so.

**Comment by ItsBlackGear** [comment]
not really, we tried to talk about it but by then i was extremely busy so i wasn't really focused and my answers confused the devs so we got to nothing 👀

**Comment by devjavu7** [comment]
Ah balls. Have a good one imma close this.

**Comment by ItsBlackGear** [comment]
still, there are alternatives
we work with simply improved terrain and quark realistic, and soon i'll be implementing the updated terrain generation in caves and cliffs backport 👀

**Comment by devjavu7** [comment]
Damn legend now works with Terraforged
