### ISSUE TITLE
Issue with DungeonCrawl

### ISSUE THREAD

**Issue by WordStormRose** [ItsBlackGear/CaveBiomeAPI#5]
Hello,

I am attempting to use both this mod (specifically for Caves and Cliffs Backport) and DungeonCrawl in my 1.16.5 modpack, but when your mods are active the dungeons of DungeonCrawl do not spawn. I have left an issue report on the DungeonCrawl mod author's page in case it is something on their end, but I figured I would let you know as well in case it can be fixed on your end.

Thank you,

Teithor

**Comment by ItsBlackGear** [comment]
oh this is weird.. i'll check on that personally, thanks for reporting this issue and i'll let you know if there's anything that i can do from my end

**Comment by WordStormRose** [comment]
You're most welcome, and thank you very much!

**Comment by dainxt** [comment]
Greetings, I'm having the same problem with [Dungeons Mod](https://www.curseforge.com/minecraft/mc-mods/dungeons-mod). Here are crashlogs when using /locate on a mod structure. https://pastebin.com/nAUtLdVP. Seems the Structure Starts are not being registered.

**Comment by InteJason** [comment]
Any update on this? just noticed that most dungeons do not spawn in my pack due to this issue

**Comment by susan3333333** [comment]
Same here with stoneholm and extcaves, no structures will spawn from those mods with this installed
