### ISSUE TITLE
Weird acting weather boundaries

### ISSUE THREAD

**Issue by TheQKnight** [ItsBlackGear/CaveBiomeAPI#6]
When you are in a desert or non-raining biome and go into a ravine while it is raining, because of the cave biomes being separate real biomes, rain pops into existence when going into the cave biomes from the surface.

Cave biomes should take into account their surface temperature and other biome data to either allow rain or not.

**Comment by ItsBlackGear** [comment]
oops, i thought that i have replied to this!, anyways, i've working on a fix for this :0
