### ISSUE TITLE
Biome terrain generation is completely messed up in the default world type when Simply Improved Terrain is installed

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [ItsBlackGear/CaveBiomeAPI#7]
Cave Biome API Version: 1.3.1
Caves and Cliffs Backport Version: 6.2
Forge version: 36.2.2
Latest Log: https://gist.github.com/NJL5390/cc2d52f3544fabbd3aa5cf9a0e9a254c

Hi,

I noticed that after updating to the latest version of Caves and Cliffs Backport and the Cave Biome API, that a lot of weird things started happening with terrain generation when I generated a default world type. 

For example, snowy biomes generate without snow, mountainous biome generate without mountains making them look exactly like the biomes around them, as well as rivers being non existent and oceans being dry.

Snowy biomes generating without snow:
![2021-08-05_11 45 59](https://user-images.githubusercontent.com/64381954/128341832-1a6730db-ccb6-441c-a437-80a826534b17.png)
This is a mountainous biome next to a snowy tundra:
![2021-08-05_11 45 53](https://user-images.githubusercontent.com/64381954/128341868-78686c8b-d29d-425f-bf53-6ef048639f5b.png)
There are supposed to be huge mountains here but it looks more like a plains biome:
![2021-08-05_12 20 18](https://user-images.githubusercontent.com/64381954/128341925-ea48ee8b-16ee-42de-b506-2594a4b5088d.png)
This is supposed to be a river:
![2021-08-05_12 18 53](https://user-images.githubusercontent.com/64381954/128341944-af8cf6eb-c3d7-41ac-aa81-a6911ab7ed74.png)
This is supposed to be a beach type biome:
![2021-08-05_12 27 21](https://user-images.githubusercontent.com/64381954/128342635-9c5d9e89-44b2-4418-8c47-6f16161efd30.png)

Everything works fine on the Caves and Cliff world type but I would rather play on the default world type because of issues relating to other mods. Would it be possible for these terrain issues to be fixed and have the default world type be more like it was in version 6.1 of Caves and Cliffs Backport?, Maybe add back the option to disable Cave Biomes entirely in case that is what is interfering with so much of the terrain generation?

Everything goes back to normal if I revert to Caves and Cliffs Backport version 6.1 and Cave Biome API 2.0. If you need me to do any testing of this issue or need any more information about this issue, just ask and I'd be happy to help!

Thanks for all the hard work you put into these mods!

**Comment by ItsBlackGear** [comment]
i've seen this issue along with simplex terrain generation, if you play in a default world things doesn't break like this, if you have a backup of the world then i would recommend you to install chocolate fix or biome id fixer

**Comment by The-Bernician-Lamb** [comment]
Those screenshots were in a default world type, that's the entire issue. I also already have Biome ID Fixer installed. This was in an entirely new world generated with the latest version of Caves and Cliffs Backport.  

This issue has nothing to do with Biomes getting changed, the problem here is that biome generation itself is being interfered with in some way so that every biome's terrain generates as flat plains while the biomes themselves still exist in the world. (i.e they still have correct weather events for the biome and generate in the correct positions, but terrain/topography itself is bugged)

If I use the Caves and Cliffs World type that's added by Caves and Cliffs Backport then the biome's terrain/topography generates correctly.  

While I do not know of any "simplex terrain generation" I am using a fair few worldgen mods so if you're not getting this issue on your end it could be a conflict with one of those.

Here's one I'm using called Simply Improved Terrain (I'm not sure if this would cause an issue or not): https://www.curseforge.com/minecraft/mc-mods/simply-improved-terrain

**Comment by ItsBlackGear** [comment]
my bad, i meant simply improved terrain and not simplex terrain generation,
simplex terrain is a fabric mod

**Comment by The-Bernician-Lamb** [comment]
Ah, Yes. I am using that one. 

Plus I have noticed that Simply Improved Terrain's Improvements don't apply to the Caves and Cliffs world type. So that makes sense as to why it only happens on the default world type.

I've found the issue already reported on Simply Improved Terrain's Github, this is the exact issue I'm having: https://github.com/KdotJPG/Simply-Improved-Terrain/issues/11

**Comment by The-Bernician-Lamb** [comment]
I don't know if there's anything that can be done about it on your end but I can confirm this is the same issue with Simply Improved Terrain that others have been having.

Either way, I'm going to use the previous versions of Cave Biome API and Caves and Cliffs Backport until this issue is resolved.

**Comment by ItsBlackGear** [comment]
oh good news, i've been informed in the discord server by someone who is following this case that the issue has been fixed already, just that the author of SIT is holding on the update for some more stuff

**Comment by The-Bernician-Lamb** [comment]
Ok Great news! I'll happily wait for this update to release then! (As long as it will still release on 1.16) Thanks!

**Comment by ItsBlackGear** [comment]
good news, this issue has been fixed and i'll release an update today that includes the fix c:
