### ISSUE TITLE
Biome textures render bug in AntiqueAtlas

### ISSUE THREAD

**Issue by MadeshaD** [ItsBlackGear/CaveBiomeAPI#8]
**Describe the bug**
The textures of biomes are not rendered when the CaveBiomeAPI 1.3.1 is installed.

**Screenshots**
![2021-08-07_22 07 49](https://user-images.githubusercontent.com/65042032/128608867-87d5e71d-71c0-4915-aa80-8aca07fe0bb0.png)

**Forge version information:**
 - Minecraft: 1.16.5
 - Forge: 36.2.2
 - AntiqueAtlas: 6.0.1
 - CaveBiomeAPI: 1.3.1

**Additional context**
There was no such problem with the CaveBiomes 2.0.

**Comment by ItsBlackGear** [comment]
sorry for the delay! thanks for letting me know about this issue, i'll rework on CBA to fix this and many other issues c:

**Comment by starryfae** [comment]
Not just Antique Atlas, it breaks the biome colors completely on it's own, just flat green everywhere.

Relevant log lines:
```

[20Aug2021 04:48:47.140] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/biome/BiomeColors (java.lang.ClassNotFoundException: null)
[20Aug2021 04:48:47.140] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.biome.BiomeColors was not found cavebiomeapi.mixins.json:BiomeColorsMixin
```

**Comment by ItsBlackGear** [comment]
this issue is fixed in the upcoming update :D
